spring:
  application:
    name: room-reservation
  datasource:
    url: jdbc:postgresql://localhost:5432/reservationdb
    username: reservation
    password: reservation
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: room-reservation-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.roomreservation"
        spring.json.value.default.type: org.example.roomreservation.reservation.infra.banktransfer.BankTransferPaymentUpdateEvent
      enable-auto-commit: false
    listener:
      ack-mode: manual
clients:
  credit-card:
    base-url: http://localhost:8081/host/credit-card-payment-api
resilience4j:
  retry:
    instances:
      creditCardPayment:
        max-attempts: 3
        wait-duration: 10ms